import Head from "next/head";
import Canvas from "../components/Canvas/Canvas";
// import Appbar from "../components/Appbar/Appbar";
// import GAME from "../types/GAME.enum";
// import { useState } from "react";

import useWasm from "hooks/useWasm";

export default function Home() {
  const wasm = useWasm();
  console.log(wasm.add(1, 2));
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          width: "100vw",
          height: "100vh",
          padding: "2em",
          display: "flex",
          flexDirection: "column",
        }}
      >
        {/* <Appbar currentGame={currentGame} setCurrentGame={setCurrentGame} /> */}
        <Canvas />
      </main>
    </>
  );
}
